### ISSUE TITLE
[RFE] Consider wiring SSL Bundles into the Tls field

### ISSUE THREAD

**Issue by space88man** [DanielLiu1123/grpc-starter#108]
### Background
Now that [SSL Bundles](https://spring.io/blog/2023/06/07/securing-spring-boot-applications-with-ssl) are a thing and Spring will create factories for SSL use-cases...

### RFE
For the `Tls` field for secure channel consider being able to request the `KeyManager`, `TrustManager` from an SSL Bundle by name:

```
spring:
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "server"
          keystore:
            location: "classpath:server.p12"
            password: "secret"
            type: "PKCS12"
```

Presently it seems the fashion for Spring services to try to consume SSL bundles to setup TLS.

```
# hypo-config
...
channels:
  - authority: 127.0.0.1:1234
    tls-bundle: server # auto-configured SslBundle
    stub: **.MyServiceBlockingStub
...
``` 

-----------
I see that my previous issue https://github.com/DanielLiu1123/grpc-starter/issues/105, is similar to this idea of having a collection of `ManagedChannel`:

```
interface ManagedChannels {//hypo-collection 
    ManagedChannel getChannel(String name);
};
```

so `ManagedChannel` can be requested by name:
```
// Simplify manual bean creation because there is a collection of ManagedChannel
// Copy this idea from SslBundles
// - don't wire individiual channels
// - wire the bundle  and pick by name
@Bean("realm-1")
MyServiceBlockingStub realm1Bean(ManagedChannels channels) {.
ManagedChannel channel = channels.getChannel("realm-1");
}
@Bean("realm-2")
MyServiceBlockingStub realm2Bean(ManagedChannels channels) {.
ManagedChannel channel = channels.getChannel("realm-2");
}

```
