### ISSUE TITLE
Fix the issue where ManagedChannelsImpl fails to retrieve the channel.

### ISSUE THREAD

**Issue by DanielLiu1123** [DanielLiu1123/grpc-starter#114]
There is an issue with the implementation of ManagedChannelsImpl:

```yaml
grpc:
  client:
    base-packages: [ io.grpc.testing, user.v1, order.v1 ]
    channels:
      - name: channel-1
        authority: localhost:9090
```

```java
@Bean
SimpleServiceGrpc.SimpleServiceBlockingStub simpleServiceBlockingStub(ManagedChannels managedChannels) {
    return SimpleServiceGrpc.newBlockingStub(managedChannels.getChannel("channel-1")); // throws exception
}
```

The problem arises because ManagedChannelsImpl relies on the cache being pre-populated. Instead, it should proactively create the channel and insert it into the cache when necessary, rather than only attempting to retrieve it from the cache.
