### ISSUE TITLE
One channel config create one single channel

### ISSUE THREAD

**Issue by DanielLiu1123** [DanielLiu1123/grpc-starter#23]
```yaml
grpc:
  client:
    channels:
      - authority: localhost:9090 
        classes:
          - io.grpc.reflection.v1alpha.ServerReflectionGrpc.ServerReflectionStub
          - io.grpc.reflection.v1alpha.ServerReflectionGrpc.ServerReflectionBlockingStub
````

Stub `ServerReflectionStub` and `ServerReflectionBlockingStub` should share one channel.
